#!/bin/sh

#########################################
# Connectivity


#########################################
# Commands to run apps
alias run.clojure.repl='java -cp ${CLOJURE_HOME}/clojure.jar clojure.lang.Repl'
alias run.jlineclojure.repl='java -cp ${CLOJURE_HOME}/jline-0.9.91.jar:${CLOJURE_HOME}/clojure.jar jline.ConsoleRunner clojure.lang.Repl'
alias run.clojure.script='java -cp ${CLOJURE_HOME}/clojure.jar clojure.main'


#########################################
# Commands to change dirs
alias to.dotfiles='cd ~/.dotfiles'
alias to.temp='cd ${MYTEMP}'
alias to.downloads='cd ${MYDOWNLOADS}'
alias to.dropbox='cd ~/Dropbox'
alias to.desktop='cd ~/Desktop'
alias to.process='cd ${MYPROCESS}'
alias to.docs='cd ${MYDOCUMENTS}'
alias to.clients='cd ~/Documents/AI-Clients-Matthew'
alias to.code='cd ${MYCODE}'
alias to.dosug='cd ~/Documents/AI-Clients-Matthew/DOSUG'
alias to.scratch='cd ${MYSCRATCH}'
alias to.teach='cd ${MYTEACH}'
alias to.ppap='cd ~/Documents/AI-Clients-Matthew/Pearson, Addison Wesley/Presentation-Patterns-Book'
alias to.github='cd ~/Documents/Code/GitHub'
alias to.homebrew='cd /usr/local/Library'

alias to.gradlecode='cd ~/Documents/Code/Gradle'
alias to.gradleware='cd ~/Documents/AI-Clients-Archived/Gradleware'
alias to.gradlebooks='cd ~/Documents/AI-Clients-Archived/Gradleware/Gradle_Books_OReilly_SVN_and_Git_Repos'
alias to.gradlebook1='cd ~/Documents/AI-Clients-Archived/Gradleware/Gradle_Books_OReilly_SVN_and_Git_Repos/oreilly-gradle-book-1'
alias to.gradleexamples='cd ~/Documents/AI-Clients-Archived/Gradleware/Gradle_Books_OReilly_SVN_and_Git_Repos/oreilly-gradle-book-examples'
alias to.gradlesamples='cd ~/Documents/Code/Gradle/gradle_core_git/subprojects/docs/src/samples'

alias to.courses='cd ${MYCOURSES}'

alias to.courses.git='cd ~/Documents/GitHub-Training-Courseware/'
alias to.courses.git.repos='cd ~/Documents/GitHub-Training-Courseware/repos'
alias to.courses.git.workshop='cd ${MYCOURSES}/Git/presentations/Git-Workshop'
alias to.courses.git.examples='cd ${MYCOURSES}/Git/repos/local_repo_examples'
alias to.courses.git.courseware='cd ${MYCOURSES}/Git/courseware'
alias to.courses.gradle='cd ~/Documents/Teach/Courses/Gradle-Fundamentals'
alias to.courses.sonar='cd ~/Documents/Teach/Courses/Sonar'
alias to.courses.jenkins='cd ~/Documents/Teach/Courses/Jenkins-CI'

alias to.devapps='cd ${MYDEVAPPS}'


#################################
# Simple Program Name Shortening
alias aq=aquamacs
alias g=git


#############################
# Utilities
alias zipall='for D in *; do zip -r "$D" "$D"; done'

alias pram.reset='sudo nvram boot-args=”-p -r”'

alias macports.cleansource='sudo port -f uninstall inactive'
alias macports.cleanold='sudo port clean --all installed'

alias rubygems.update='sudo gem update --system'
alias macports.update='sudo port selfupdate && sudo port upgrade outdated'
alias brew.update='brew update && brew upgrade'

alias timemachine.enablelocalversions='sudo tmutil enablelocal'
alias timemachine.disablelocalversions='sudo tmutil disablelocal'

alias hexdumpfile='od -h'

# Flush the DNS on Mac
alias network.dnsflush='dscacheutil -flushcache'

# Copy and paste and prune the usless newline
alias pbcopynn='tr -d "\n" | pbcopy'

# Set the extended MacOS attributes on a file such that Quicklook will open it as text
alias finder.astext='xattr -wx com.apple.FinderInfo "54 45 58 54 21 52 63 68 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00" $1'
#alias finder.qltext2='osascript -e tell application "Finder" to set file type of ((POSIX file "$1") as alias) to "TEXT"'

# Git Scribe Commands
alias gitscribe.gp='git scribe gen pdf && open output/book.pdf'
alias gitscribe.gh='git scribe gen html && open output/book.html'

# Show network connections
# Often useful to prefix with SUDO to see more system level network usage
alias network.connections='lsof -l -i +L -R -V'
alias network.established='lsof -l -i +L -R -V | grep ESTABLISHED'
alias network.internalip="ifconfig en0 | egrep -o '([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)'"
alias network.externalip='curl -s http://checkip.dyndns.org/ | sed "s/[a-zA-Z<>/ :]//g"'

# Files used, anywhere on the filesystem
alias files.usage='sudo fs_usage -e -f filesystem|grep -v CACHE_HIT|grep -v grep'
# Files being opened
alias files.open='sudo fs_usage -e -f filesystem|grep -v CACHE_HIT|grep -v grep|grep open'
# Files in use in the Users directory
alias files.usage.user='sudo fs_usage -e -f filesystem|grep -v CACHE_HIT|grep -v grep|grep Users'

# Directory listings
# LS_COLORS='no=01;37:fi=01;37:di=07;96:ln=01;36:pi=01;32:so=01;35:do=01;35:bd=01;33:cd=01;33:ex=01;31:mi=00;05;37:or=00;05;37:'
# -G Add colors to ls
# -l Long format
# -h Short size suffixes (B, K, M, G, P)
# -p Postpend slash to folders
alias ls='ls -G -h -p '
alias ll='ls -l -G -h -p '

# Teaching Functions
alias class.resethello='to.courses.git.repos;cd hellogitworld-bare.git; git push --mirror'
alias class.simpleprompt='export PS1=" $ "'

#########################################
# Utility Functions

# Restart Apache on Mac
alias apacherestart="sudo /usr/sbin/apachectl restart"

# Do a Matrix movie effect of falling characters
function matrix1() {
echo -e "\e[1;40m" ; clear ; while :; do echo $LINES $COLUMNS $(( $RANDOM % $COLUMNS)) $(( $RANDOM % 72 )) ;sleep 0.05; done|gawk '{ letters="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789@#$%^&*()"; c=$4; letter=substr(letters,c,1);a[$3]=0;for (x in a) {o=a[x];a[x]=a[x]+1; printf "\033[%s;%sH\033[2;32m%s",o,x,letter; printf "\033[%s;%sH\033[1;37m%s\033[0;0H",a[x],x,letter;if (a[x] >= $1) { a[x]=0; } }}'
}

function matrix2() {
echo -e "\e[1;40m" ; clear ; characters=$( jot -c 94 33 | tr -d '\n' ) ; while :; do echo $LINES $COLUMNS $(( $RANDOM % $COLUMNS)) $(( $RANDOM % 72 )) $characters ;sleep 0.05; done|gawk '{ letters=$5; c=$4; letter=substr(letters,c,1);a[$3]=0;for (x in a) {o=a[x];a[x]=a[x]+1; printf "\033[%s;%sH\033[2;32m%s",o,x,letter; printf "\033[%s;%sH\033[1;37m%s\033[0;0H",a[x],x,letter;if (a[x] >= $1) { a[x]=0; } }}'
}

function matrix3() {
echo -e "\e[1;40m" ; clear ; while :; do echo $LINES $COLUMNS $(( $RANDOM % $COLUMNS)) $( printf "\U$(( $RANDOM % 500 ))" ) ;sleep 0.05; done|gawk '{c=$4; letter=$4;a[$3]=0;for (x in a) {o=a[x];a[x]=a[x]+1; printf "\033[%s;%sH\033[2;32m%s",o,x,letter; printf "\033[%s;%sH\033[1;37m%s\033[0;0H",a[x],x,letter;if (a[x] >= $1) { a[x]=0; } }}'
}

# Use Mac OSX Preview to open a man page in a more handsome format
function manp() {
  man -t $1 | open -f -a /Applications/Preview.app
}

# Show normally hidden system and dotfile types of files
# in Mac OSX Finder
function finder.showhiddenfiles() {
  defaults write com.apple.Finder AppleShowAllFiles YES
  osascript -e 'tell application "Finder" to quit'
  sleep 0.25
  osascript -e 'tell application "Finder" to activate'
}

# Hide (back to defaults) normally hidden system and dotfile types of files
# in Mac OSX Finder
function finder.hidehiddenfiles() {
  defaults write com.apple.Finder AppleShowAllFiles NO
  osascript -e 'tell application "Finder" to quit'
  sleep 0.25
  osascript -e 'tell application "Finder" to activate'
}

# Get (cache) all Cheat sheets
function cheat.getall() {
	cheat sheets | grep '^  ' | xargs -n 1 -I {} bash -c 'cheat {} | :'
}

function find.name() {
  wild=\'\*$1\*\'
  sh -c "find . -iname $wild"
}

alias lessc='less -R' # Lets color escape sequences carry through to less
alias morec='more -R'
alias lesscolor='less -R'
alias morecolor='more -R'

function screenshot.setjpg() {
    defaults write com.apple.screencapture type jpg
    killall SystemUIServer
}

function screenshot.setpng() {
    defaults write com.apple.screencapture type png
	killall SystemUIServer
}
